# -*- coding: utf-8 -*-
"""essai 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_H_zp46HQqCapeMRGnZEGREH1dFhK3je
"""

import requests
import pandas as pd

api_url = "https://berita-indo-api-next.vercel.app/api/cnn-news/teknologi"

response = requests.get(api_url)

data = response.json()
data_list = data.get('data', [])

# Membuat DataFrame dari data_list
df = pd.DataFrame(data_list)

df